# Spring Boot Configuration
spring.application.name=dream-vacation
server.port=8080

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/dream_vacation
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=dream_vacation_user
spring.datasource.password=IsjZbzOkzevnr1JMHREsj7zG3gaDJm9U

# JPA/Hibernate Configuration (PostgreSQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO
logging.level.com.dreamvacation=DEBUG
